:carrier:
  - Alaska Communications
  - Alltel
  - Appalachian Wireless
  - AT&T
  - BELL Atlantic Mobile
  - Bluegrass Cellular
  - Boost Mobile
  - <b>Product Identifiers</b>
  - Cellcom
  - Cellular South
  - Chatr
  - Cincinnati Bell
  - Cingular
  - Consumer Cellular
  - Cricket
  - C-Spire
  - Factory Unlocked
  - Fido
  - GreatCall
  - Koodo Mobile
  - MetroPCS
  - Metro PCS
  - Net10
  - nTelos
  - Page Plus Cellular
  - Rogers Wireless
  - Sasktel
  - Seller Unlocked
  - Solavei
  - Solo Mobile
  - Sprint
  - Straight Talk
  - Telcel America
  - Telus
  - Ting
  - T-Mobile
  - TracFone
  - Unlocked
  - U.S. Cellular
  - Verizon
  - Virgin Mobile
  - Virgin Mobile (CA)
  - Wind Mobile

:color:
  - 12-bit (4096 colors)
  - 16-bit (65000 colors)
  - 18-bit (262000 Colors)
  - Active blue
  - Airy Blue
  - Aluminium Grey/Black
  - Aluminum gray
  - Amber Brown
  - Amethyst Purple
  - Aqua
  - Aqua Blue / White
  - Arctic Blue
  - Atlantic blue
  - Berry Red
  - Black
  - Black and Slate
  - Black/Black
  - Black blue
  - Black Gray
  - Black / Illuvial Black
  - Black Mist
  - Black on Silver
  - Black Orange
  - Black/Pink
  - Black/red
  - Black silver
  - Black & Slate
  - Black steel
  - Black to chrome fade
  - Black to pink fade
  - Black White
  - Black Yellow
  - Blue
  - Blue Arctic
  - Blue black
  - Blue Gradient
  - Blue gray
  - Blue ice
  - Blue Mint
  - Blue silver
  - Bluish Black
  - Bordeaux
  - Boulevard black
  - <b>Product Identifiers</b>
  - Bronze
  - Bronze black
  - Brown
  - Brown Autumn
  - Bubblegum pink
  - Burgundy
  - Canary yellow
  - Carbon
  - Carbon black
  - Carbon blue
  - Caviar Black
  - Ceramic White
  - Champagne
  - Charcoal
  - Charcoal black
  - Charcoal gray
  - Charcoal Yellow
  - Cherry black
  - Cherry blossom pink
  - Chic white
  - Chocolate
  - Chocolate Black
  - Chrome Black
  - Classic blue
  - Classic Gray
  - Classic White
  - Coffee
  - Coffee brown
  - Cool gray
  - Cool silver
  - Copper Gold
  - Cosmic black
  - Cosmic blue
  - Cosmic silver
  - Cosmopolitan white
  - Cupid pink
  - Cyan
  - Dark
  - Dark blue
  - Dark brown
  - Dark gray
  - Dark gray chrome
  - Dark Green
  - Dark metal
  - Dark pearl gray
  - Dark red
  - Dark sapphire
  - Dark Slate
  - Dark Titanium Gray
  - Deep black
  - Deep blue
  - Deep gray
  - Deep Ocean
  - Deep plum
  - Dive Blue
  - Earth green
  - Ebony black
  - Ebony Grey & Spot Yellow
  - Electric black
  - Electric blue
  - Emerald
  - Emerald black
  - Emerald Gray
  - Energetic red
  - Fancy red
  - Fire
  - Flame Black
  - Galaxy blue
  - Garnet red
  - Glamour red
  - Glossy black
  - Glossy Red
  - Gold
  - Golden White
  - Graphite
  - Graphite gray
  - Gray
  - Gray Silver
  - Green
  - Green on Black
  - Grey
  - Hatha violet
  - Heather grape
  - Hot pink
  - Hourglass
  - Ice silver
  - Indigo black
  - Indigo Blue
  - Jamaican yellow
  - Jet black
  - Khaki
  - Lavender
  - Licorice
  - Light blue
  - Light Green
  - Light yellow
  - Lilac
  - Lime
  - Lime green
  - Luminous white
  - Lunar Grey
  - Luna White
  - Luster white
  - Luxury Brown
  - Magenta
  - Magnetic gray
  - Mahogany
  - Mandarin
  - Marble White
  - Maroon
  - Matte Black
  - Mauve
  - Metallic black
  - Metallic blue
  - Metallic gray
  - Metallic silver
  - Metal silver
  - Metro pink
  - Midnight black
  - Midnight blue
  - Midnight Silver
  - Mineral black
  - Mirror black
  - Mirror Gray
  - Misty black
  - Mocha
  - Modern black
  - Moon Gray
  - Mysterious black
  - Mysterious green
  - Mystic black
  - Navy
  - Navy blue
  - Night black
  - Night blue
  - Noble black
  - Obsidian
  - Obsidian black
  - Ocean blue
  - Onyx black
  - Orange
  - Orange Flare
  - Orchid
  - Pale gold
  - Peachy Pink
  - Pearl gray
  - Pearl Magenta
  - Pearl white
  - Pebble Blue
  - Petrol blue
  - Phantom Black
  - Phantom gray
  - Piano black
  - Pink
  - Pink Twilight
  - Platinum
  - Plum
  - Polar white
  - Precious black
  - Premium silver
  - Progressive black
  - Pure white
  - Purple
  - Purple Mirage
  - Raspberry Pink
  - Red
  - Red Aurora
  - Red gradient
  - Red on white
  - Rocky silver
  - Rose Gold
  - Rose pink
  - Royal pink
  - Royal purple
  - Rythm black
  - Sakura Pink
  - Sapphire
  - Sapphire Black
  - Sapphire blue
  - Satin black
  - Satin pink
  - Scarlet red
  - Seagull silver
  - Sensuous black
  - Shadow black
  - Silver
  - Silver black
  - Silver blue
  - Silver charcoal
  - Silver gray
  - Silver moon
  - Silver on black
  - Silver white
  - Slate black
  - Slate blue
  - Slate gray
  - Smoky violet
  - Snow white
  - Soft black
  - Solid black
  - Sophisticated Black
  - Space Gray
  - Sparkling silver
  - Speed black
  - Spring rose
  - Stainless steel
  - Stealth Blue
  - Steel black
  - Steel gray
  - Steel silver
  - Strong Black
  - Style white
  - Sweet pink
  - Swift black
  - Teal
  - Tech Silver
  - Tin silver
  - Titan gray
  - Titanium
  - Titanium gray
  - Titanium silver
  - Topaz blue
  - Transition black
  - Turquoise
  - Two-tone blue
  - Ultramarine blue
  - Urban gray
  - Vapour silver
  - Velvet black
  - Vibrant orange
  - Violet
  - Vivid Blue
  - Vortex Black
  - Warm gray
  - Warm Silver
  - White
  - White and Silver
  - White-Black
  - White-Blue
  - White Frost
  - White / Orange
  - White pearl
  - White silver
  - White & Silver
  - White steel
  - White yellow
  - Wine red
  - Winter white
  - Yellow